### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by ghost** [bettercallazamat/TheNewYorkTimes-clone-project#1]
Outstanding job guys! here are some notes so you can improve:

-Get rid of empty spaces divs, try to use different paragraphs.
-Use floats.
-Uppercase.
-Position absolute it may overlap in a small screen.

**Comment by bettercallazamat** [comment]
1) we enclosed each paragraph with a separate p tag
2) used float, thanx for reminding 
3) uppercase rule in the footer is for time-saving purposes
4) created a separate media-queries branch with styles for responsiveness
